### PR TITLE
Fixing StakingHotkeys index

### LINKED ISSUE #2201: Missing StakingHotkeys
Some hotkeys are present in Alpha map (and have non-zero stake), but are missing in StakingHotkeys map. This results in adverse side-effects like missing these hotkeys in root claim, for example, or staking precompile returning a wrong number for getTotalColdkeyStake.

1. Find the root cause and fix it
2. Write migration that will add these missing hotkeys in StakingHotkeys

Attached is the current snapshot of this constraint violation, to be used for debugging, not for migration.

[staking-hotkeys-failures.txt](https://github.com/user-attachments/files/23511185/staking-hotkeys-failures.txt)

### PR DESCRIPTION
**Pull request by grbIzl**
## Description
Migration was introduced that adds missing coldkey<->hotkey pairs into StakingHotkeys index.

## Related Issue(s)

- Closes #2201 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `./scripts/fix_rust.sh` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

### CODE REVIEW

File: pallets/subtensor/src/migrations/migrate_fix_staking_hot_keys.rs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+        );
+        return weight;
+    }
+
+    let mut cache: BTreeMap<T::AccountId, Vec<T::AccountId>> = BTreeMap::new();
+    let mut storage_reads: u64 = 0;
+    let mut storage_writes: u64 = 0;
+
+    for ((hotkey, coldkey, _netuid), alpha) in Alpha::<T>::iter() {
+        if alpha == 0 {
```
Comment (open-junius) [inline pallets/subtensor/src/migrations/migrate_fix_staking_hot_keys.rs:28]: There is a read for Alpha, need update weight. Alpha is a big map, it is better to find other storage to find out missed (cold, hot) relation.

Comment (grbIzl) [reply pallets/subtensor/src/migrations/migrate_fix_staking_hot_keys.rs:28]: Thanks @open-junius ! I added the forgotten weight. As for the Alfa map idea: I understand your concern but StakingHotkeys is literally index for Alfa map (please correct me if I'm wrong) and one of its goals is indeed to replace some costly calls to Alfa map. In this case using different map for (cold, hot) relation (like Owner map) doesn't make sense to me. Wdyt?

Comment (open-junius) [reply pallets/subtensor/src/migrations/migrate_fix_staking_hot_keys.rs:28]: It is fine if we have to loop the storage this way.

**Review by open-junius — APPROVED** [review]
Looks good for me.

**Review by l0r1s — APPROVED** [review]
